---
- name: wait for k8s node to appear
  delegate_to: localhost
  connection: local
  shell: |
      #!/bin/bash
      n=0
      until [ $n -ge 5 ]
      do
         kubectl --namespace={{ wait_for_namespace|default("default") }} get {{ wait_for_resource_type }} {{ wait_for_resource_name }} && break  # substitute your command here
         n=$[$n+1]
         echo "."
         sleep 1
      done
      kubectl --namespace={{ wait_for_namespace|default("default") }} get {{ wait_for_resource_type }} {{ wait_for_resource_name }}
  args:
    executable: /bin/bash

